#
# Terraform Destroy
#
- hosts: localhost
  tasks:

    - name: Terraform Destroy
      community.general.terraform:
        project_path: 'terraform/'
        state: absent
        force_init: yes
        init_reconfigure: yes
        variables_files: "./tf.tfvars"
        backend_config:
          region: "ap-northeast-1"
          bucket: "keyamamo-demo3"
          key: "{{ my_tf_key }}"
        variables: 
           TF_VAR_tag: ""
           TF_VAR_expire: ""
