#
# Terraform Run
#
- hosts: localhost
  tasks:
    - name: Terraform Run
      community.general.terraform:
      #https://docs.ansible.com/ansible/latest/collections/community/general/terraform_module.html
      #cloud.terraform.terraform:

        project_path: 'terraform/'
        state: present
        force_init: yes
        init_reconfigure: yes
        variables_files: "./tf.tfvars"
        backend_config:
          region: "ap-northeast-1"
          bucket: "keyamamo-demo3"
          key: "{{ my_tf_key }}"
        variables: 
           TF_VAR_tag: "{{ my_tf_key }}"
           TF_VAR_expire: "{{ lookup('pipe', 'date --date \"1 days\" +%Y-%m-%d') }}"
          #  TF_VAR_expire: "{{ lookup('pipe', 'date --date \"1 days\" +%Y-%m-%dT%H:%M:%S') }}"

    - name: Inventory Update
      ansible.builtin.meta: refresh_inventory
