#
# とりあえず使わない。p2に統合、p2で設定した仮パスを送らないといけないため。
# Notification 
#
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Send message
      slack:
        token: "{{ slack_token }}"
        channel: '#ansible-demo'
        msg: |
          Ansible Automation Platformより
          以下のSandbox環境の準備が完了しました( 管理番号 {{ my_tf_key }} )

    - name: Send message
      slack:
        token: "{{ slack_token }}"
        channel: '#ansible-demo'
        msg: | 
          >{{ item }} 
          >{{ hostvars[item].random_password }}
      loop: "{{ groups['tag_myGroup_' + my_tf_key] }}"
      vars:
        item: "{{ inventory_hostname }}"

