---
#
# Create Cloudwatch alerts
#
- name: Register EC2 instance with specific tag to CloudWatch Events Timer
  hosts: localhost
  gather_facts: False
  vars:
    # tag_name: myGroup
    # tag_value: YourTagValue

  tasks:
    - name: Gather EC2 facts with specific tag
      amazon.aws.ec2_instance_info:
        region: "ap-northeast-1"
        filters:
          "tag:myGroup": "{{ my_tf_key }}"
          instance-state-name: running
      register: ec2_facts
        
    - name: Print debug
      debug:
        var: ec2_facts   

    - name: Create CloudWatch Alarm for EC2 instance
      amazon.aws.cloudwatch_metric_alarm:
        region: "ap-northeast-1"
        state: present
        name: "{{ 'demo-EC2 Instance State Monitoring-' + item.instance_id }}"
        description: "This is a description for the alarm"
        metric: "StatusCheckFailed"
        namespace: "AWS/EC2"
        statistic: Average
        comparison: "GreaterThanThreshold"
        threshold: 0
        period: 60
        evaluation_periods: 1
        alarm_actions:
          - "arn:aws:sns:ap-northeast-1:667830292567:demo-EC2-CloudWatch-Notification"
        dimensions:
          # InstanceId: "i-0c7ac3ca1f1b77eab"
          InstanceId: "{{ item.instance_id }}"
      with_items: "{{ ec2_facts.instances }}"

