---
# Update the status of a ServiceNow Request Item to "Closed Complete"

- name: Create ServiceNow Incident using servicenow.itsm module
  hosts: localhost
  gather_facts: no
  vars:
    # sys_id: 
  tasks:
  - name: Update status of requested item
    servicenow.itsm.api:
      instance:
          host: https://dev114831.service-now.com
          username: "{{ sn_username }}"
          password: "{{ sn_password }}"
      resource: sc_req_item
      action: patch
      sys_id: "{{ sys_id }}"
      data:
        short_description: demo-description2
        state: 1100 #Closed Complete
    register: result

  - name: Print ServiceNow Response
    debug:
      var: result
